version: "3.9"
services:
  server:
    build: .
    depends_on:
      - db
    ports:
      - 3000:3000
    restart: always
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'admin@cd123'
      MYSQL_DATABASE: 'blog'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin@cd123'
    ports:
      - 3306:3306